CREATE DATABASE IF NOT EXISTS shop ;

USE shop;

CREATE TABLE IF NOT EXISTS user(
	id INT  UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL UNIQUE,
	password CHAR(32) NOT NULL,
	email VARCHAR(255) NOT NULL DEFAULT '',
	birth INT,
	sex TINYINT NOT NULL DEFAULT 1,
	tel VARCHAR(255),
	reg_time INT NOT NULL,
	log_time INT,
	address TEXT
)ENGINE=MyISAM DEFAULT CHARSET=utf8;


-------------
--2014年4月22日user表中插入状态,权限
--statue/ 0:禁用   1:启用
--admin/ 0:超级管理员 2:管理员  3:会员

ALTER TABLE user ADD statue TINYINT NOT NULL DEFAULT 1;
ALTER TABLE user ADD admin TINYINT NOT NULL DEFAULT 3;

----2014年4月23日user表中插入头像,注册ip,登录ip

ALTER TABLE user ADD icon VARCHAR(255);
ALTER TABLE user ADD reg_ip VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE user ADD last_ip VARCHAR(255) NOT NULL DEFAULT '';


-----2014年cate

CREATE TABLE IF NOT EXISTS cate(
	id INT  UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL DEFAULT '',
	pid	INT NOT NULL,
	path VARCHAR(255) NOT NULL
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

---添加首页导航字段

ALTER TABLE cate ADD nav TINYINT NOT NULL DEFAULT 0;

---添加首页列表字段

ALTER TABLE cate ADD list TINYINT NOT NULL DEFAULT 0;

------goods商品表

CREATE TABLE IF NOT EXISTS goods(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	cate_id INT UNSIGNED,
	name VARCHAR(255) NOT NULL DEFAULT '',
	price DECIMAL(10,2) NOT NULL,
	num INT UNSIGNED,
	is_up TINYINT NOT NULL DEFAULT 1,
	up_time INT,
	down_time INT,
	is_best TINYINT NOT NULL DEFAULT 1,
	is_hot TINYINT NOT NULL DEFAULT 1,
	is_new TINYINT NOT NULL DEFAULT 1,
	`describe` TEXT
)ENGINE=MyISAM DEFAULT CHARSET=utf8;


ALTER TABLE goods ADD visited INT NOT NULL DEFAULT '0';

-----goods_img商品图片表

CREATE TABLE IF NOT EXISTS goods_img(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	goods_id INT UNSIGNED NOT NULL,
	name VARCHAR(255),
	is_face TINYINT NOT NULL DEFAULT 0
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

----地址表 user_address

CREATE TABLE IF NOT EXISTS user_address(
	id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	user_id INT NOT NULL,
	receiver VARCHAR(255) NOT NULL,
	address VARCHAR(255) NOT NULL,
	tel VARCHAR(255) NOT NULL,
	email VARCHAR(255)

);


ALTER TABLE user_address ADD zip VARCHAR(20);
ALTER TABLE user_address ADD `derault` TINYINT DEFAULT '0';




----订单表 order_info
CREATE TABLE IF NOT EXISTS order_info(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	order_num VARCHAR(255) NOT NULL,
	user_id INT NOT NULL,
	receiver VARCHAR(255) NOT NULL,
	address VARCHAR(255) NOT NULL,
	tel VARCHAR(255) NOT NULL,
	email VARCHAR(255),
	createtime INT NOT NULL,
	total DECIMAL(10,2) NOT NULL,
	status TINYINT NOT NULL DEFAULT 0

)ENGINE=MyISAM DEFAULT CHARSET=utf8;


--添加邮编
ALTER TABLE order_info ADD zip VARCHAR(20);

----订单商品表 order_goods

CREATE TABLE IF NOT EXISTS order_goods(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	order_info_id INT NOT NULL,
	goods_id INT NOT NULL,
	goods_num INT UNSIGNED,
	price DECIMAL(10,2) NOT NULL
)ENGINE=MyISAM DEFAULT CHARSET=utf8;


---评论表

CREATE TABLE IF NOT EXISTS comments(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	order_info_id INT NOT NULL,
	order_goods_id INT NOT NULL,
	comments TEXT,
	statue TINYINT NOT NULL DEFAULT 1
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

---积分表 user_account

CREATE TABLE IF NOT EXISTS user_account(
	id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	user_id INT UNSIGNED NOT NULL,
	rank_points INT NOT NULL DEFAULT 0 ,
	pay_points INT NOT NULL DEFAULT 0 ,  /*需删除*/
	chang_time INT ,
	change_desc VARCHAR(255)
)ENGINE=MyISAM DEFAULT CHARSET=utf8;



