CREATE DATABASE IF NOT EXISTS shop ;

USE shop;

CREATE TABLE IF NOT EXISTS user(
	id INT  UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL UNIQUE,
	password CHAR(32) NOT NULL,
	emile VARCHAR(255) NOT NULL DEFAULT '',
	birth INT,
	sex TINYINT NOT NULL DEFAULT 1,
	tel VARCHAR(255),
	reg_time INT NOT NULL,
	log_time INT,
	address TEXT
)ENGINE=MyISAM DEFAULT CHARSET=utf8;